///|
pub extend CheckError with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Finding with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Finding with ToJson::{to_json}

///|
pub extend Header with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Header with ToJson::{to_json}

///|
pub extend Report with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Report with ToJson::{to_json}

///|
pub extend SignalCounts with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend SignalCounts with ToJson::{to_json}

///|
pub extend SystemCounts with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend SystemCounts with ToJson::{to_json}

///|
pub extend Window with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Window with ToJson::{to_json}
